<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D2GVCL39" ignored="3" name="regression(failed)" tests="20" failures="12" timestamp="2022-07-26T20:56:48 IST" time="102.695" errors="0">
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.014" classname="dependend.test.cases.DependentTestCasesClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dependend.test.cases.DependentTestCasesClass2.verifyUserCanLoginWithValidUserNameAndPassword(DependentTestCasesClass2.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLoginWithValidUserNameAndPassword -->
  <testcase name="verifyUserCanReadEmail" time="0.002" classname="assertions.AssertionClass">
    <failure type="java.lang.AssertionError" message="Current share price is not matching expected [405.55] but found [405.55]">
      <![CDATA[java.lang.AssertionError: Current share price is not matching expected [405.55] but found [405.55]
at assertions.AssertionClass.verifyUserCanReadEmail(AssertionClass.java:45)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="verifyuserslist" time="0.001" classname="assertions.AssertionClass">
    <failure type="java.lang.AssertionError" message="expected [45] but found [23]">
      <![CDATA[java.lang.AssertionError: expected [45] but found [23]
at assertions.AssertionClass.verifyuserslist(AssertionClass.java:55)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyuserslist -->
  <testcase name="verifyUserCanSendEmail" time="0.001" classname="assertions.AssertionClass">
    <failure type="java.lang.AssertionError" message="expected [null] but found [anno.AnnoClass@4bb4de6a]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [anno.AnnoClass@4bb4de6a]
at assertions.AssertionClass.verifyUserCanSendEmail(AssertionClass.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyfileupload" time="58.983" classname="annotation.FileUploadTestCase">
    <failure type="java.lang.AssertionError" message="expected [1 file has been successfully uploaded.] but found [1 file
has been successfully uploaded.]">
      <![CDATA[java.lang.AssertionError: expected [1 file has been successfully uploaded.] but found [1 file
has been successfully uploaded.]
at annotation.FileUploadTestCase.verifyfileupload(FileUploadTestCase.java:64)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyfileupload -->
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.01" classname="assertions.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	User name is not displayed expected [true] but found [false],
	deleted user is displayed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User name is not displayed expected [true] but found [false],
deleted user is displayed expected [false] but found [true]
at assertions.SoftAssertionClass.verifyUserCanLoginWithValidUserNameAndPassword(SoftAssertionClass.java:25)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLoginWithValidUserNameAndPassword -->
  <testcase name="verifyUserCanReadEmail" time="0.002" classname="assertions.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [null] but found [anno.AnnoClass@2e6a5539]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [null] but found [anno.AnnoClass@2e6a5539]
at assertions.SoftAssertionClass.verifyUserCanReadEmail(SoftAssertionClass.java:46)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="verifyUserCanSendEmail" time="0.002" classname="assertions.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	values is not matching expected [45] but found [23]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
values is not matching expected [45] but found [23]
at assertions.SoftAssertionClass.verifyUserCanSendEmail(SoftAssertionClass.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyLinksAreBrockenOrNot" time="18.21" classname="brockenlink.BrockenLinkClass5ToolQA3">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	https://demoqa.com/bad-request is brcken with status code = 400 expected [true] but found [false],
	https://demoqa.com/unauthorized is brcken with status code = 401 expected [true] but found [false],
	https://demoqa.com/forbidden is brcken with status code = 403 expected [true] but found [false],
	https://demoqa.com/invalid-url is brcken with status code = 404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
https://demoqa.com/bad-request is brcken with status code = 400 expected [true] but found [false],
https://demoqa.com/unauthorized is brcken with status code = 401 expected [true] but found [false],
https://demoqa.com/forbidden is brcken with status code = 403 expected [true] but found [false],
https://demoqa.com/invalid-url is brcken with status code = 404 expected [true] but found [false]
at brockenlink.BrockenLinkClass5ToolQA3.verifyLinksAreBrockenOrNot(BrockenLinkClass5ToolQA3.java:57)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLinksAreBrockenOrNot -->
  <testcase name="verifyNewUserCanBeAddedWithProvidedData" time="0.0" classname="dataprovider.annotation.DataProviderClass3">
    <skipped/>
  </testcase> <!-- verifyNewUserCanBeAddedWithProvidedData -->
  <testcase name="verifyUserCanSendEmail" time="0.002" classname="invocation.InvocationCountClass"/>
  <testcase name="verifyUserCanSendEmail" time="0.002" classname="invocation.InvocationCountClass"/>
  <testcase name="verifyUserCanSendEmail" time="0.004" classname="invocation.InvocationCountClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at invocation.InvocationCountClass.verifyUserCanSendEmail(InvocationCountClass.java:16)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyUserCanSendEmail" time="0.001" classname="invocation.InvocationCountClass"/>
  <testcase name="verifyUserCanSendEmail" time="0.001" classname="invocation.InvocationCountClass"/>
  <testcase name="sample" time="0.0" classname="invocation.InvocationCountClass">
    <skipped/>
  </testcase> <!-- sample -->
  <testcase name="sampleTestCase" time="12.217" classname="screen.cpature.ScreenCaptureClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at screen.cpature.ScreenCaptureClass2.sampleTestCase(ScreenCaptureClass2.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sampleTestCase -->
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.002" classname="dependend.test.cases.DependentTestCasesClass"/>
  <testcase name="verifyUserCanSendEmail" time="0.001" classname="dependend.test.cases.DependentTestCasesClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dependend.test.cases.DependentTestCasesClass.verifyUserCanSendEmail(DependentTestCasesClass.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanSendEmail -->
  <testcase name="verifyUserCanReadEmail" time="0.0" classname="dependend.test.cases.DependentTestCasesClass">
    <skipped/>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="verifyUserCanReadEmail" time="0.0" classname="dependend.test.cases.DependentTestCasesClass2">
    <ignored/>
  </testcase> <!-- verifyUserCanReadEmail -->
  <testcase name="verifyUserCanLoginWithValidUserNameAndPassword" time="0.0" classname="assertions.AssertionClass">
    <ignored/>
  </testcase> <!-- verifyUserCanLoginWithValidUserNameAndPassword -->
  <testcase name="verifyUserCanSendEmail" time="0.0" classname="dependend.test.cases.DependentTestCasesClass2">
    <ignored/>
  </testcase> <!-- verifyUserCanSendEmail -->
</testsuite> <!-- regression(failed) -->
